<a href="https://colab.research.google.com/github/sandeeppalakkal/ML_Datascience_Practice/blob/master/PyTorch_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

In [0]:
# Pytorch tensors
x = torch.rand(5,3)
y = torch.ones(5,3)

In [3]:
print(x)

tensor([[0.3689, 0.3252, 0.9715],
        [0.5771, 0.7490, 0.2808],
        [0.7953, 0.5222, 0.5272],
        [0.9920, 0.5958, 0.5171],
        [0.0562, 0.6241, 0.4278]])


In [4]:
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [0]:
# Addition syntax 1
z = torch.add(x,y)

In [6]:
print(z)

tensor([[1.3689, 1.3252, 1.9715],
        [1.5771, 1.7490, 1.2808],
        [1.7953, 1.5222, 1.5272],
        [1.9920, 1.5958, 1.5171],
        [1.0562, 1.6241, 1.4278]])


In [7]:
# Tensor shape syntax 1
print(x.shape)

torch.Size([5, 3])


In [8]:
# Tensor shape syntax 2
print(x.size())

torch.Size([5, 3])


In [9]:
# Addition syntax 2
print(x+y)

tensor([[1.3689, 1.3252, 1.9715],
        [1.5771, 1.7490, 1.2808],
        [1.7953, 1.5222, 1.5272],
        [1.9920, 1.5958, 1.5171],
        [1.0562, 1.6241, 1.4278]])


In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
  print("CUDA device is not available")

tensor([[1.4101, 1.4473, 1.5356],
        [1.2186, 1.3727, 1.4489],
        [1.8789, 1.2695, 1.4725],
        [1.3535, 1.3267, 1.7715],
        [1.2827, 1.8754, 1.5448]], device='cuda:0')
tensor([[1.4101, 1.4473, 1.5356],
        [1.2186, 1.3727, 1.4489],
        [1.8789, 1.2695, 1.4725],
        [1.3535, 1.3267, 1.7715],
        [1.2827, 1.8754, 1.5448]], dtype=torch.float64)


In [10]:
# Tensor type
print(type(x))

<class 'torch.Tensor'>


In [12]:
# view() = reshape()
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
# Reshaped!
print(x)
print(y)
print(z)

tensor([[ 0.6335, -1.2514,  0.8108, -0.9873],
        [ 0.6529,  1.4345,  0.2457,  0.8810],
        [ 0.7574, -0.7626,  0.0663,  0.2342],
        [ 0.4868, -0.6574,  1.6877,  0.9089]])
tensor([ 0.6335, -1.2514,  0.8108, -0.9873,  0.6529,  1.4345,  0.2457,  0.8810,
         0.7574, -0.7626,  0.0663,  0.2342,  0.4868, -0.6574,  1.6877,  0.9089])
tensor([[ 0.6335, -1.2514,  0.8108, -0.9873,  0.6529,  1.4345,  0.2457,  0.8810],
        [ 0.7574, -0.7626,  0.0663,  0.2342,  0.4868, -0.6574,  1.6877,  0.9089]])


In [17]:
# item() to convert a single tensor element to a number
print(x[0,0])
print(x[0,0].item())

tensor(0.6335)
0.6335106492042542


In [18]:
# Converting to numpy array
print(x)
print(x.numpy())

tensor([[ 0.6335, -1.2514,  0.8108, -0.9873],
        [ 0.6529,  1.4345,  0.2457,  0.8810],
        [ 0.7574, -0.7626,  0.0663,  0.2342],
        [ 0.4868, -0.6574,  1.6877,  0.9089]])
[[ 0.63351065 -1.2514378   0.810836   -0.9873469 ]
 [ 0.6529109   1.4345037   0.24565032  0.88096434]
 [ 0.7573738  -0.76259947  0.06630369  0.23422599]
 [ 0.48679796 -0.65741533  1.6876866   0.9089124 ]]
