<a href="https://colab.research.google.com/github/sandeeppalakkal/ML_Datascience_Practice/blob/master/PyTorch_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

In [0]:
x = torch.rand(5,3)
y = torch.ones(5,3)

In [0]:
print(x)

tensor([[0.4101, 0.4473, 0.5356],
        [0.2186, 0.3727, 0.4489],
        [0.8789, 0.2695, 0.4725],
        [0.3535, 0.3267, 0.7715],
        [0.2827, 0.8754, 0.5448]])


In [0]:
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [0]:
z = torch.add(x,y)

In [0]:
print(z)

tensor([[1.4101, 1.4473, 1.5356],
        [1.2186, 1.3727, 1.4489],
        [1.8789, 1.2695, 1.4725],
        [1.3535, 1.3267, 1.7715],
        [1.2827, 1.8754, 1.5448]])


In [0]:
print(x.shape)

torch.Size([5, 3])


In [0]:
print(x.size())

torch.Size([5, 3])


In [0]:
print(x+y)

tensor([[1.4101, 1.4473, 1.5356],
        [1.2186, 1.3727, 1.4489],
        [1.8789, 1.2695, 1.4725],
        [1.3535, 1.3267, 1.7715],
        [1.2827, 1.8754, 1.5448]])


In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
  print("CUDA device is not available")

tensor([[1.4101, 1.4473, 1.5356],
        [1.2186, 1.3727, 1.4489],
        [1.8789, 1.2695, 1.4725],
        [1.3535, 1.3267, 1.7715],
        [1.2827, 1.8754, 1.5448]], device='cuda:0')
tensor([[1.4101, 1.4473, 1.5356],
        [1.2186, 1.3727, 1.4489],
        [1.8789, 1.2695, 1.4725],
        [1.3535, 1.3267, 1.7715],
        [1.2827, 1.8754, 1.5448]], dtype=torch.float64)
