<a href="https://colab.research.google.com/github/sandeeppalakkal/ML_Datascience_Practice/blob/master/TensorFlow_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow Practice

Reference: Introduction to TensorFlow, Google Cloud, [Coursera](https://www.coursera.org/learn/intro-tensorflow/home/welcome)

In [0]:
import tensorflow as tf

### Defining a DAG

In [14]:
a = tf.constant([1,3,4])
b = tf.constant([4,3,2])
c = tf.add(a,b)
print(c)

Tensor("Add_1:0", shape=(3,), dtype=int32)


### Running a Session

In [15]:
with tf.Session() as sess:
  result = sess.run(c)
  print(result)

[5 6 6]


In [16]:
print(result)
print(type(result))

[5 6 6]
<class 'numpy.ndarray'>


### Different Ways of Running a Session & Printing Results

In [0]:
x = tf.constant([3,5,7])
y = tf.constant([1,2,3])
z1 = tf.add(x,y)
z2 = x * y
z3 = z2 - z1

In [18]:
print(z2)

Tensor("mul_1:0", shape=(3,), dtype=int32)


In [19]:
with tf.Session() as sess:
  print(sess.run(z3))

[-1  3 11]


In [20]:
with tf.Session() as sess:
  print(z3.eval())

[-1  3 11]


In [21]:
with tf.Session() as sess:
  a1,a2 = sess.run([z1,z3])
  print(a1)
  print(a2)

[ 4  7 10]
[-1  3 11]


In [22]:
with tf.Session() as sess:
  print(sess.run([z1]))

[array([ 4,  7, 10], dtype=int32)]


### TensorFlow Eager Evaluation (Non-Lazy)

In [0]:
# Nead to restart the kernel to make this code working due to TF Eager
import tensorflow as tf
from tensorflow.contrib.eager.python import tfe

In [2]:
tfe.enable_eager_execution()
x = tf.constant([3,5,7])
y = tf.constant([1,2,3])
x - y #printed due to Eager running

<tf.Tensor: id=2, shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

### Visualizing Graph

In [0]:
import tensorflow as tf

In [0]:
# Add 'name = "x"' to label nodes in TensorBoard visualization
x = tf.constant([3,5,7],name="x")
y = tf.constant([1,2,3],name="y")
z1 = tf.add(x,y,name="z1")
z2 = x * y
z3 = z2 - z1

In [0]:
with tf.Session() as sess:
  # Write the session graph to summary directory
  with tf.summary.FileWriter('summaries',sess.graph) as writer:
    a1,a2 = sess.run([z1,z3])

In [10]:
!ls summaries

events.out.tfevents.1551144653.705d8b69932a
events.out.tfevents.1551144700.705d8b69932a
events.out.tfevents.1551144701.705d8b69932a
events.out.tfevents.1551144704.705d8b69932a


In [0]:
# Need ngrok tunnelling to run TensorBoard from Colab
# Ref: https://www.dlology.com/blog/quick-guide-to-run-tensorboard-in-google-colab/
from google.datalab.ml import TensorBoard
TensorBoard().start('./summaries')

### Tensors in TF

A TF graph consists of tensors and operations.

In [25]:
x = tf.constant([[[1,2,3],[4,5,6]]])
print(x)

Tensor("Const_6:0", shape=(1, 2, 3), dtype=int32)


In [27]:
print(x.shape)

(1, 2, 3)


In [53]:
x = tf.constant(10)
print(x.shape)
x = tf.constant([10])
print(x.shape)
x = tf.constant([10,10])
print(x.shape)
x = tf.constant([[10,10],[10,10]])
print(x.shape)
x = tf.constant([[[10,10,10],[10,10,10]]])
print(x.shape)
x = tf.constant([[[10,10,10],[10,10,10],[10,10,10]]])
print(x.shape)
x = tf.constant([[[10,10,10],[10,10,10],[10,10,10]],[[10,10,10],[10,10,10],[10,10,10]]])
print(x.shape)

()
(1,)
(2,)
(2, 2)
(1, 2, 3)
(1, 3, 3)
(2, 3, 3)


In [55]:
x = tf.constant(10)
print(x.shape)
x = tf.stack([x,x])
print(x.shape)
x = tf.stack([x,x,x])
print(x.shape)
x = tf.stack([x,x,x,x])
print(x.shape)
x = tf.stack([x,x])
print(x.shape)

()
(2,)
(3, 2)
(4, 3, 2)
(2, 4, 3, 2)


In [56]:
x = tf.constant([10,10])
print(x.shape)

(2,)


### Slicing of a Tensor

In [61]:
x = tf.constant([[3,5,7],[4,6,8]])
y = x[:,1]
z = x[1,:]
with tf.Session() as sess:
  a1,a2,a3 = sess.run([x,y,z])
  print("x = ", a1)
  print("y = ",a2)
  print("z = ",a3)

x =  [[3 5 7]
 [4 6 8]]
y =  [5 6]
z =  [4 6 8]


### Reshaping a Tensor

In [70]:
x = tf.constant([[3,5,7],[4,6,8]])
y = tf.reshape(x,[3,2])
z = tf.reshape(x,[3,2])[2,:]
print(x.shape,y.shape)

(2, 3) (3, 2)


In [71]:
with tf.Session() as sess:
  print('x = ', x.eval())
  print('y = ', y.eval())
  print('z = ', z.eval())

x =  [[3 5 7]
 [4 6 8]]
y =  [[3 5]
 [7 4]
 [6 8]]
z =  [6 8]


### Variables

In [0]:
def forward_pass(w,x):
  return tf.matmul(w,x)

def train_loop(x,n_iter=3):
  # Defien scope for w and tell TF to reuse the w from previous definition
  with tf.variable_scope("model",reuse=tf.AUTO_REUSE):
    # Define the variable, w
    w = tf.get_variable("weights",
                       shape=(1,2), #shape 1x2
                       initializer=tf.truncated_normal_initializer(), #init
                       trainable=True) #trainable or not
    preds = []
    for k in range(n_iter):
      preds.append(forward_pass(w,x))
      w = w + 0.1
    return preds

In [89]:
with tf.Session() as sess:
  #preds = train_loop(tf.constant([[3.2,5.1,7.2],[4.3,6.2,8.3]])) #2x3 matrix
  preds = train_loop(tf.constant([[1.,1.,1.,2.],[1.,1.,1.,2.]])) #2x4 matrix
  # initialization of all the variables together
  tf.global_variables_initializer().run()
  for i in range(len(preds)):
    print("{}:{}".format(i,preds[i].eval()))

0:[[-2.6512108 -2.6512108 -2.6512108 -5.3024216]]
1:[[-2.4512105 -2.4512105 -2.4512105 -4.902421 ]]
2:[[-2.2512107 -2.2512107 -2.2512107 -4.5024214]]


### Placeholders

Allow you to feed in values, such as by reading from a text file.

In [90]:
a = tf.placeholder("float",None)
b = a * 4
print(a)
with tf.Session() as sess:
  print(sess.run(b,feed_dict={a:[1,2,4]}))

Tensor("Placeholder:0", dtype=float32)
[ 4.  8. 16.]
